### ISSUE TITLE
Return JSON on 404

### ISSUE THREAD

**Issue by cancan101** [4Catalyzer/flask-resty#110]
Return a 404 in JSON formatting.

**Comment by taion** [comment]
We should do this for all errors coming out of API views.

**Comment by taion** [comment]
The problem here is – what about on an app with some Flask-RESTy views and some non-Flask-RESTy views? What if the non-Flask-RESTy views aren't meant to expose JSON-speaking APIs?

Maybe for "stock" error types, we should look at the prefix?

**Comment by itajaja** [comment]
I am not sure how much is worth to consider this case. fr is oriented towards building microservices, so I think that assuming everything in the service is a rest endpoint is quite fair

**Comment by taion** [comment]
I wonder if this means this whole thing would work better as a blueprint.

**Comment by taion** [comment]
Resolved by #149
