### ISSUE TITLE
Docs Question

### ISSUE THREAD

**Issue by j-walker23** [4Catalyzer/flask-resty#132]
Hey, i have been reading over the source trying to see if this lib handles creating/updating relationships of the main model being created/updated.

I am looking for something like that. Does this lib do anything if the incoming json object to a POST/PUT method has relationships also in json?

**Comment by taion** [comment]
It's via `related`/`Related`. Pending better docs (any docs, really), take a look at https://github.com/4Catalyzer/flask-resty/blob/master/tests/test_related.py, which shows the rough API. It should look something like:

```py
class ParentView(GenericModelView):
    model = models.Parent
    schema = schemas.ParentSchema()

    related = Related(
        children=ChildView,
    )
```

**Comment by taion** [comment]
It might seem a bit odd that this goes through the view, but that's a deliberate choice – in this context we want to be able to reuse the auth helpers on the child view, and going through the view in this case gives that to us for free.
