### ISSUE TITLE
init_app method did not save app reference 

### ISSUE THREAD

**Issue by JefferyLondon** [4Catalyzer/flask-resty#280]
Hi,

I've been playing this library since yesterday, and using it with factory create_app mode. 
```
def register_extensions(app):
    from .extensions import login_manager, migrate, cache, ma, api
    from .database import db

    db.init_app(app)
    ma.init_app(app)
    migrate.init_app(app, db)
    cache.init_app(app)
    api.init_app(app)

```
however pytest throws an error as below, from latest version (v0.21.1)

```
――――――――――――――――――――――――――――――――――――――――――― ERROR at setup of test_api_asset_get_bad_url_format ――――――――――――――――――――――――――――――――――――――――――――

request = <SubRequest 'app' for <Function test_api_asset_get_bad_url_format>>

>   ???

C:\dev\xx-data_2\tests\conftest.py:16:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
app\app.py:21: in create_app
    register_blueprints(app)
app\app.py:60: in register_blueprints
    from app.api import api_bp
app\api\__init__.py:4: in <module>
    from . import asset
app\api\asset.py:35: in <module>
    api.add_resource("/widgets", AssetListView, AssetView)
..\xx-data\venv\lib\site-packages\flask_resty\api.py:127: in add_resource
    app = self._get_app(app)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <flask_resty.api.Api object at 0x000001FFE7AAE5F8>, app = None

    def _get_app(self, app):
        app = app or self._app
>       assert app, "no application specified"
E       AssertionError: no application specified
E       assert None

..\xx-data\venv\lib\site-packages\flask_resty\api.py:79: AssertionError
----------------------------------------------------------- Captured stdout setup -----------------------------------------------------------
ktmw32
                                                                                                                                17% █▋

```

Apparently the init_app function forgot to save the app reference after digging into the source code.

```
    def init_app(self, app):
        """Initialize an application for use with Flask-RESTy.
        :param app: The Flask application object.
        :type app: :py:class:`flask.Flask`
        """
        app.extensions["resty"] = FlaskRestyState(self)

        app.register_error_handler(ApiError, handle_api_error)
        app.register_error_handler(HTTPException, handle_http_exception)

```

So I've been wondering... you guys don't use factory mode to create app? :)

Jeffery

**Comment by taion** [comment]
We in fact don't use factory mode, but this is the correct behavior for a Flask extension.

See e.g. http://flask.pocoo.org/docs/1.0/extensiondev/#the-extension-code or the code for Flask-SQLAlchemy. When using factory mode, extensions should not bind to the application, as the extension may be used with multiple applications.

As such, when using factory mode, you need to explicitly pass in `app` to `Api.add_resource` and `Api.add_ping`, to identify _which_ of the potentially many apps you're using.

**Comment by JefferyLondon** [comment]
> We in fact don't use factory mode, but this is the correct behavior for a Flask extension.
> 
> See e.g. http://flask.pocoo.org/docs/1.0/extensiondev/#the-extension-code or the code for Flask-SQLAlchemy. When using factory mode, extensions should not bind to the application, as the extension may be used with multiple applications.
> 
> As such, when using factory mode, you need to explicitly pass in `app` to `Api.add_resource` and `Api.add_ping`, to identify _which_ of the potentially many apps you're using.


Right, it make sense. I will close the pull request. Thanks for the quick reply.

However, the syntax for passing the app in `add_resource` is quite redundant. I copy and changed the `routes.py` from example

```
# example/routes.py

from flask_resty import Api
from flask import current_app
from . import app, views

api = Api(app, prefix="/api")

api.add_resource("/authors/", views.AuthorListView, views.AuthorView, app=current_app)
api.add_resource("/books/", views.BookListView, views.BookView, app=current_app)
api.add_ping("/ping/", app=current_app)

```

Is there a way to import it?

**Comment by taion** [comment]
You can't in general use `flask.current_app` there, because `flask.current_app` is only defined when you're working in an "app context". In other words, in general it's only applicable when handling a request.

Otherwise, at top level, attempting to use `flask.current_app` will actually give you a `RuntimeError`. And in general it's not expected that you'll be in an app context when setting up your routes.

We could add support for checking `flask.current_app`, but I don't expect it'd be very useful here. Unless you explicitly made use of something like `app.app_context()`... but then you may as well make a partially-bound version of `app.add_resource` that already binds the `app` argument.

**Comment by JefferyLondon** [comment]
Actually I still prefer the quick fix I made in the init_app function. And I think it’s safe even in app factory mode.

Or maybe something like this to get around it:

```
def register_extensions(app):
    from .extensions import api

    api.init_app(app)
    api._app = app.     # <——-

```

**Comment by JefferyLondon** [comment]
Actually I search through the plugins I used before, and found some of them did link the app/extension together.

Flask-mongoengine:
https://github.com/MongoEngine/flask-mongoengine/blob/a0b0cf80ec321d29baca743e4075101db6be7d68/flask_mongoengine/__init__.py#L113

Flask-login:
https://github.com/maxcountryman/flask-login/blob/fd2f3f993b6b74761c9a57a0a792e66a239b1195/flask_login/login_manager.py#L116

Flask-socketio 
https://github.com/miguelgrinberg/Flask-SocketIO/blob/547675843d09c367b90bfca5df0890b568dca79d/flask_socketio/__init__.py#L191

**Comment by taion** [comment]
Those extensions are violating an explicit guideline from the Flask extension documentation:

![image](https://user-images.githubusercontent.com/3112159/60998881-db4fc180-a327-11e9-8deb-c2fddc672408.png)

You can certainly bind `api._app` yourself if you'd like, though.

**Comment by JefferyLondon** [comment]
Now I understand why flask-apispec is using the deferred array here: 

https://github.com/jmcarp/flask-apispec/blob/b51962ab1db3ed856e6030058366175b215162af/flask_apispec/extension.py#L62

This solved my initial problem of registering resources without app. What do you think?

**Comment by taion** [comment]
This still isn't technically correct, though. Per the Flask docs, for a given extension, when using `init_app`, it must support use with multiple apps, which means, as noted above, it should "not assign `app` to `self`".

**Comment by taion** [comment]
This has been open for a while, and I think the current behavior is what Flask says extensions should do. I'm going to close it out for now, unless there's anything else to discuss here.
