### ISSUE TITLE
api actions?

### ISSUE THREAD

**Issue by JefferyLondon** [4Catalyzer/flask-resty#285]
Hi,

`flask-resty` has done a good job with CRUD apis like
```
/users/
/users/<id>/
```
what about the action apis similar to following?
```
/users/<id>/follow
/users/<id>/posts
```
What's the best way to implement these apis along with flask-resty? putting blueprints and class view into same file isn't a good idea

**Comment by itajaja** [comment]
yes, that's very common.

something like `/users/<id>/follow` looks like a sub-action, and we usually do something like

```py
api.add_resource('/users/<id>/follow', FollowView)

class FollowView(UsersBaseView):
    deserializer = None

    @get_item_or_404
    def put(self, user):
        # put your logic here, you can use existing flask-resty methods to reuse logic
```

regarding `/users/<id>/posts` that looks more like a subresource, so it would be different. for example:

```
class UserPosts(UsersBaseView):
    @property
    def query(self):
        return super().query.filter_by(user_id=flask.request.view_args["id"])
```

**Comment by taion** [comment]
Yup, we've been doing it more or less as @itajaja says – something like:

```python
class UserViewBase(GenericModelView):
    # ...


class UserListView(UserViewBase):
    def get(self):
        return self.list()


class UserView(UserViewBase):
    def get(self, id):
        return self.retrieve(id)


class UserFollowView(UserViewBase):
    @get_item_or_404
    def put(self, user):
        # ...
```

And then set up separate routes for all of these. We've been thinking of adding an easier way to do this, but it's a little awkward to break the boundaries between views and route. And also schemas/&c. are naturally tied to the view class.

So I'd like to have an API that makes attaching these sorts of actions easier, but I'm not quite sure how I'd want it to look, yet.
