### ISSUE TITLE
unable to import JwtAuthentication

### ISSUE THREAD

**Issue by tracethompson** [4Catalyzer/flask-resty#287]
Hi!

I'm unable to import the JwtAuthentication class.
(`ImportError: cannot import name 'JwtAuthentication' from 'flask_resty'`)

maybe the import is failing [here](https://github.com/4Catalyzer/flask-resty/blob/master/flask_resty/__init__.py#L41)?

**Comment by taion** [comment]
If you're using the JWT classes, you need to install Flask-RESTy as `flask-resty[jwt]` to pull in the proper dependencies. Otherwise those imports won't exist.

We should probably revise the API here a bit, because cases like this are a little confusing, but for now this is what we have.

**Comment by tracethompson** [comment]
thanks 👍

**Comment by tracethompson** [comment]
Hey one more question - is there documentation on generating the jwt according to what the `JwtAuthentication` class expects?

**Comment by taion** [comment]
Oh, we didn't document the JWT part, eh? They should just be any standard JWT. The ones from e.g. `jwt.io` should do. They should work with e.g. any OpenID Connect ID tokens, for example.

See e.g. https://github.com/4Catalyzer/flask-resty/blob/master/tests/test_jwt.py.

**Comment by tracethompson** [comment]
ah thanks! was looking for those config keys
