### ISSUE TITLE
TypeError: 'MyDataModel' object is not subscriptable

### ISSUE THREAD

**Issue by heckad** [4Catalyzer/flask-resty#290]
```
..\resources\profiles.py:44: in put
    return self.update(id, partial=True)
C:\Users\Asus\.virtualenvs\corpteam-site-NCnneqC8\lib\site-packages\flask_resty\view.py:1104: in update
    data_in = self.get_request_data(expected_id=id, partial=partial)
C:\Users\Asus\.virtualenvs\corpteam-site-NCnneqC8\lib\site-packages\flask_resty\view.py:246: in get_request_data
    return self.deserialize(data_raw, **kwargs)
C:\Users\Asus\.virtualenvs\corpteam-site-NCnneqC8\lib\site-packages\flask_resty\view.py:713: in deserialize
    data = super().deserialize(data_raw, **kwargs)
C:\Users\Asus\.virtualenvs\corpteam-site-NCnneqC8\lib\site-packages\flask_resty\view.py:292: in deserialize
    self.validate_request_id(data, expected_id)
C:\Users\Asus\.virtualenvs\corpteam-site-NCnneqC8\lib\site-packages\flask_resty\view.py:360: in validate_request_id
    id = self.get_data_id(data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <resources.profiles.ProfileView object at 0x00000151FF735D88>
data = <ProfileModel (transient 1451689744328)>

    def get_data_id(self, data):
        if len(self.id_fields) == 1:
            try:
>               return data[self.id_fields[0]]
E               TypeError: 'ProfileModel' object is not subscriptable
```

It seems like a violation in logic. After `data = schema_load(self.deserializer, data_raw, **kwargs)` in `ApiView.deserialize` data is a `ProfileModel` istead of dict in marshmellow 3.

**Comment by sloria** [comment]
Schemas must return dictionaries, not ORM instances. This is why we [recommend using TableSchema instead of ModelSchema](https://flask-resty.readthedocs.io/en/latest/special_topics.html#usage-with-marshmallow-sqlalchemy), or a `Schema` subclass with `field_for`.

**Comment by heckad** [comment]
I changed type but now it fails with code `422:invalid_id.missing`. I send a request on the endpoint with `id` but `flask-resty` try to extract it from data and not try to get it from `request.view_args`. It's a bug?

**Comment by taion** [comment]
The default behavior in Flask-RESTy follows JSON API in requiring `id` to be specified in "update" payload in the data as well: https://jsonapi.org/format/#crud-updating

We've found this useful in a few cases because it allows us to do additional type validation on IDs, beyond what's easily possible with Werkzeug matchers.

This is a little awkward to override at the moment. You can try doing something like:

```python
def deserialize(self, data_raw, *, expected_id=None, **kwargs):
    if expected_id:
        expected_id = False  # Or None if you want to allow but ignore it.

    return super().deserialize(data_raw, expected_id=expected_id, **kwargs)
```
