### ISSUE TITLE
Authorization before data validation

### ISSUE THREAD

**Issue by heckad** [4Catalyzer/flask-resty#292]
How to make that authorization was executed before the validation of data. This is necessary so that an unauthorized user does not recognize the data scheme since now the response has 422 code with a description of what is not correct in the request instead of 401.

**Comment by taion** [comment]
The documentation here could be a little bit better in https://flask-resty.readthedocs.io/en/latest/api.html#authorization, but the `authorize_request` hook runs before any data validation (or any processing of the data at all). In this hook, you can check e.g. `flask.request.method`, or do any other checks you want on the current authentication, and raise an `ApiError` as needed.

Though note that 401 is the status code for "credentials invalid", not "current action prohibited".

**Comment by heckad** [comment]
> Though note that 401 is the status code for "credentials invalid", not "current action prohibited".

I want the only admin to do data modification operations. What code shod be return if data manipulation operation does some authorized user(not admin)?

**Comment by taion** [comment]
Generally that's a 403: https://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses

**Comment by sloria** [comment]
Closing for now. Feel free to comment if there are any follow-up questions.
