### ISSUE TITLE
Allow registration of resources before app is available

### ISSUE THREAD

**Issue by 5uper5hoot** [4Catalyzer/flask-resty#319]
Hi all,

I believe #280 is related to this.

Thanks for the library, I've been using for a little while now and as I was already using Flask/SQLAlchemy/Marshmallow, I've found using flask-resty to be a nice little productivity boost.

I was hoping to get some feedback on an implementation for deferring resource registration until an App is available.

Take the below project structure:
```
.
└── app
    ├── __init__.py
    ├── ext
    │   ├── api.py
    │   └── db.py
    ├── models
    │   ├── __init__.py
    │   └── country.py
    └── resources
        └── country
            ├── __init__.py
            └── country.py
```
With the current implementation of `Api` I do this:
```py
# app/__init__.py

from flask import flask

from .ext import api, db
from .resources.country import CountryListView, CountryView

def create_app(config=None):
    app = app(__name__)
    ...
    api.init_app(app)
    api.add_resource(
        "/country",
        country.country_api.CountryListView,
        country.country_api.CountryView,
        app=app,
        id_rule="<int:id>",
    )
    ...
```
This is no problem, but I find that as the number of resources grows, my `create_app()` function is getting quite long.  So I made this wrapper around Api:

```py
# app/ext/api.py
from flask_resty.api import Api as Api_


class Api(Api_):
    def __init__(self, app=None, prefix=""):
        super().__init__(app, prefix)
        # add a container for holding deferred registrations
        self._deferred_registrations = []

    def _get_app(self, app):
        # this method no longer raises AssertionError
        app = app or self._app
        return app

    def init_app(self, app):
        super().init_app(app)

        # if there are deferred registrations, add them now that the app is available.
        for deferred in self._deferred_registrations:
            self.add_resource(*deferred[0], app=app, **deferred[1])

    def add_resource(self, *args, app=None, **kwargs):
        # first check if we have the app, and if not, defer the registration
        app = self._get_app(app)
        if app is None:
            self._deferred_registrations.append((args, kwargs))
        else:
            super().add_resource(*args, app=app, **kwargs)


api = Api(prefix="/api")
```
Which then allows me to register the resources closer to their implementation, e.g.:
```py
# app/resources/country/__init__.py
from ...ext import api
from . import country 

api.add_resource(
    "/country",
    country.CountryListView,
    country.CountryView,
    id_rule="<int:id>",
)
```
And `create_app()` stays nice and simple:
```py
# app/__init__.py
from flask import flask

from .ext import api, db

# import resources before calling `api.init_app()`
from .resources import country  # noqa: F401

def create_app(config=None):
    app = app(__name__)
    ...
    api.init_app(app)
    ...
```

This implementation of `App` should be backward compatible as the only change in existing behavior is that it no longer will raise `AssertionError` if the app is not available when the resource is added.

I was wondering if there are any pitfalls with this approach that I should consider, and if this or something related might be considered for merging upstream?

**Comment by taion** [comment]
Yup, so we're in the process of moving from a structure like:

```
- models.py
  * class Foo(db.Model)
  * class Bar(db.Model)
- schemas.py
  * class FooSchema(Schema)
  * class BarSchema(Schema)
- views.py
  * class FooView(GenericModelView)
  * class BarView(GenericModelView)
- routes.py
  * api = Api(...)
  * api.add_resource('/foos', ...)
  * api.add_resource('/bars', ...)
```

To a structure that looks more like:

```
- __init__.py
  * api = Api(...)
- resources/
  - foo.py
    * class Foo(db.Model)
    * class FooSchema(Schema)
    * class FooView(GenericModelView)
    * api.add_resource('/foos', ...)
  - bar.py
    * class Bar(db.Model)
    * class BarSchema(Schema)
    * class BarView(GenericModelView)
    * api.add_resource('/bars', ...)
```

You need to be a little careful with backrefs between modules in certain cases (especially if using marshmallow-sqlalchemy), as it's possible due to import order concerns that lazily evaluated models in backrefs haven't actually been defined yet, but otherwise this seems better for us.

Could I ask why you're deferring app initialization, though? These routes/resources seem pretty tightly coupled to an app?

**Comment by 5uper5hoot** [comment]
> Could I ask why you're deferring app initialization, though?

I don't always, its just a case by case thing, and mainly having a fresh app instance per test and testing different configs.

**Comment by taion** [comment]
@sloria do you have any thoughts here on whether it'd make sense to add deferred route registration support here? it seems a bit odd to do here, just because we don't know which app they should belong to.

i think what you're doing is fine, but i think the app registration semantics that flask suggests means we don't have a good way to do this deferred bookkeeping for you, such that the right thing is for you to continue to do this bookkeeping yourself

**Comment by 5uper5hoot** [comment]
Thanks, no probs either way and I appreciate the feedback on the solution.
