### ISSUE TITLE
Additive Filtering

### ISSUE THREAD

**Issue by peterschutt** [4Catalyzer/flask-resty#336]
I have a base view that defines quite a few filters that is shared across a few different views. On one of the sub-class views I want to add another `ColumnFilter`, e.g.:

```py

class BaseView(GenericModelView):
    ...
    filtering = Filtering(...)

class SubclassView(BaseView):
    ...
    filtering = ...  # I want to add a filter to the BaseView filtering without it affecting the other sub-classes.
```
I've done this:

```py
from flask_resty.filtering import Filtering as Filtering_

class Filtering(Filtering_):
    def __add__(self, other):
        if not isinstance(other, Filtering):
            return NotImplemented
        new = Filtering()
        new._arg_filters = dict(**self._arg_filters)
        new._arg_filters.update(other._arg_filters)
        return new
```

So on the sub-class I then do:

```py

class SubclassView(BaseView):
    ...
    filtering = BaseView.filtering + Filtering(another=ColumnFilter(...))
```

Is there a supported way to do this type of thing?

**Comment by sloria** [comment]
This would be nice. I suggested the same thing here: https://github.com/4Catalyzer/flask-resty/issues/236#issuecomment-528996665 . I think it'd technically be more correct to use the union operator. 

Feel free to send a PR!

**Comment by taion** [comment]
Yup; for now, the best way to do this is to define a dictionary, and do something like:

```py
filtering = Filtering(
    **BASE_FILTERS,
    another=operator.eq,
)
```
