### ISSUE TITLE
does it support generating swagger document from marshlmallow?

### ISSUE THREAD

**Issue by johnson329** [4Catalyzer/flask-resty#339]
flask-apispec，I found that the author of fastapi recomended it，but it has a simple document.
do you recomend using id in production enviroment?

**Comment by itajaja** [comment]
we did have support for swagger some time ago, but we dropped it. I don't think you can use flask-apispec with flask-resty, but you could use https://github.com/marshmallow-code/apispec to generate at least part of the spec. right @sloria ?

**Comment by sloria** [comment]
That's correct--you can use apispec together with this library. Take a look at the apispec plugin https://github.com/4Catalyzer/flask-resty/tree/v0.20.13/flask_resty/spec . We ended up removing it because we were not using it ourselves, but it should still work with few modifications.
