### ISSUE TITLE
how to ahive filtering across relationship?

### ISSUE THREAD

**Issue by johnson329** [4Catalyzer/flask-resty#341]
https://github.com/philipn/django-rest-framework-filters#filtering-across-relationships
if support:
    how?
else:
  any advice?

**Comment by r1b** [comment]
You can use `ModelFilter` or the `model_filter` decorator and create an arbitrary filter expression against the model. That expression can access relationships on the model - you will just need to be sure those relationships have been loaded (e.g with `query_options`) before you try to filter on their fields.

**Comment by r1b** [comment]
Closing, please re-open if this is still not clear
