### ISSUE TITLE
Access query parameters in GET

### ISSUE THREAD

**Issue by paulkatich** [4Catalyzer/flask-resty#365]
Hello I am trying to access query parameter in a GET to perform the logic of my function. I am using request_args method but this fails. I defined an args schema as well. But still fails with TypeError: 'dict' object is not callable. If access as flask.request.args it works but it is failing when access with flask resty framework. Is there different approach where I can access query parameters ?

Method call to access query params:
self.request_args()

error: TypeError: 'dict' object is not callable

**Comment by itajaja** [comment]
it's simply `self.request_args`, no `()` :)
