### ISSUE TITLE
Tutorial example doesn't work

### ISSUE THREAD

**Issue by UralmashFox** [4Catalyzer/flask-resty#366]
The example from https://flask-resty.readthedocs.io/en/latest/guide.html fails when running "flask run" with the following error:
* Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

**Comment by itajaja** [comment]
hi! the readme says to specify a FLASK_APP argument, are you doing it?

```
FLASK_APP=example FLASK_ENV=development flask run
```

make sure you are running this from the repo root

**Comment by itajaja** [comment]
that's not how environmental variables work :) you either have to do (notice they are on the same line!):

```sh
FLASK_APP=example FLASK_ENV=development flask run
```

or (notice export):

```sh
export FLASK_APP=example
export FLASK_ENV=development
flask run
```

hope this helps
