### ISSUE TITLE
Allow Specifying the Expected Scheme in JwtAuthentication for Authorization Header

### ISSUE THREAD

**Issue by cancan101** [4Catalyzer/flask-resty#83]
Currently it is hardcoded as `Bearer`.

**Comment by taion** [comment]
Sure – make https://github.com/4Catalyzer/flask-resty/blob/master/flask_resty/jwt.py#L64 a class property. Then classes extending `JwtAuthentication` can override that.

**Comment by cancan101** [comment]
What do you think for the property name? How about `header_prefix` for consistency with: http://getblimp.github.io/django-rest-framework-jwt/#additional-settings.

**Comment by taion** [comment]
:-1: on "prefix". The term for this is "scheme", per the spec, so it should be something like `header_scheme`.

**Comment by cancan101** [comment]
@taion I actually couldn't find it explicitly called out in the spec as the name.

**Comment by taion** [comment]
See http://xml2rfc.ietf.org/public/rfc/html/rfc2617.html.

```
credentials = auth-scheme #auth-param
```

**Comment by cancan101** [comment]
Okay. How about `header_auth_scheme`?

**Comment by taion** [comment]
I think it's redundant given that this is already `JwtAuthentication`. Would kind of scheme would it be if not an auth scheme?

**Comment by cancan101** [comment]
Could be a requirement to use `https` (Scheme) for example.

**Comment by taion** [comment]
That's why it'd be `header_scheme` though.
